language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: JOBS=4
      addons:
        apt:
          packages:
            - libboost1.55-all-dev
            - libode-dev
            - libeigen3-dev
            - freeglut3-dev
            - libassimp-dev
      cache:
        apt: true
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: JOBS=2
      cache:
        directories:
          - /usr/local

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew tap dartsim/dart;
      brew tap homebrew/science;
      brew update;
      brew install homebrew/science/libccd;
      brew install dartsim/dart/fcl;
      brew install boost ode eigen assimp;
    else
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -y update;
      sudo apt-get -y install g++-5;
      export CXX=g++-5;
      if [ ! -e /usr/local/lib/libfcl.so ]; then
        wget -O - https://github.com/danfis/libccd/archive/v2.0.tar.gz | tar zxf - ;
        cd libccd-2.0;
        cmake .;
        sudo make install;
        cd ..;
        wget -O - https://github.com/flexible-collision-library/fcl/archive/0.5.0.tar.gz | tar zxf - ;
        cd fcl-0.5.0;
        cmake .;
        sudo make install;
        cd ..;
      fi;
    fi

script:
  # get OMPL subrepository
  - git clone --depth=1 --branch=master git://github.com/ompl/ompl.git

  - mkdir -p build
  - cd build
  - cmake -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp ..
  - make -j $JOBS
  - ctest -j $JOBS
